### ISSUE TITLE
Thoughts on Creating SimpleSurvey As a NuGet Package?

### ISSUE THREAD

**Issue by taylorchasewhite** [ADefWebserver/BlazorSimpleSurvey#2]
This work seems really great, and is similar to something I'd like to do in my blazor application. Have you thought at all about creating this as a NuGet package so that people can plug and play into their applications?

**Comment by ADefWebserver** [comment]
The application needs a database and is really only meant to be an example for using Azure B2C. No further development is planned. Thanks
