### ISSUE TITLE
Question on creating standalone or hosted blazor app for user management in B2C.

### ISSUE THREAD

**Issue by vpallathu** [ADefWebserver/BlazorSimpleSurvey#3]
I'm very impressed by your solution on managing the users in B2C. I have been struggling for a few months to achieve the same without any success.

I have a few questions on your solution.

1. Is the BlazorSimpleSurvey a standalone or hosted Blazor app?
2. Can I follow any of the documents to create an application that gives the basic code necessary?

- [hosted blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
- [standalone blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0#authentication-package)

I appreciate your feedback.

**Comment by ADefWebserver** [comment]
@vpallathu - Thank you for the kind words.  **Blazor Simple Survey** is a _Server Side Blazor_ app not a _Blazor WebAssembly_ app. To set up your own application, please follow the directions here: https://medium.com/marcus-tee-anytime/azure-ad-b2c-quickstart-with-visual-studio-blazor-563efdff6fdd

**Comment by vpallathu** [comment]
I followed the instructions from your article. But I got the following error when I try to login:

```Message contains error: 'unauthorized_client', error_description: 'AADB2C90057: The provided application is not configured to allow the 'OAuth' Implicit flow.```

I had to select the following option on the **application authentication** page to rectify that:

```Access tokens (used for implicit flows)```

With that selection, I'm able to see the login page. Please note that when I created the **user flow**, I selected a few claims that have to be returned. I'm not sure whether that requires the **implicit flows** to be turned on.

**Comment by ADefWebserver** [comment]
Yeah that is covered in the **Marcus Tee** article (at: https://medium.com/marcus-tee-anytime/azure-ad-b2c-quickstart-with-visual-studio-blazor-563efdff6fdd). If you look in the comments you will see that I posted the exact same fix.

**Comment by vpallathu** [comment]
I'm now [reading your blog](https://blazorhelpwebsite.com/ViewBlogPost/43) to create the views. I already created an **application** by following the instructions in the previous article. Should I use the same application which I created already to set up the access to the **Microsoft Graph** or should I create a new application in *B2C*?

What I'm trying to do is create a few groups like **family 1, family 2, family 3**. Each **family** will have an administrator and a few members. The administrator of each **family** can manage the users login information. Do you know how I should structure the groups, users and the user information to manage multiple **families**?

**Comment by ADefWebserver** [comment]
@vpallathu - This is just my opinion:

- You can have multiple applications that use the same **Azure B2C** tenant
- You organize things by creating **roles** and putting **users** into those roles
- This allows a **user** to have different abilities based on the **roles** that they are in

Therefore, (in my opinion):

- You can create, in **Azure B2C**, a role called "**Family Administrator**"
- A user in the "**Family Administrator**" role can create new "**Family Members**" (this can be, but does not need to be, a **role** in **Azure B2C**)
- You can track what users belong to a family in your SQL database (see how I track what Surveys belong to a user here: https://github.com/ADefWebserver/BlazorSimpleSurvey/wiki (The **UserId** field in the **Survey** table)

**Comment by vpallathu** [comment]
In the next few days I will give you feedback on this. Thank you so much for your help.

**Comment by vpallathu** [comment]
I don't think I can create **Roles** under **B2C**. I have to create the **Roles** in the default **Active Directory**. There are some people recommending to use **B2C custom attribute** an discouraging to use **Active Directory**.

Here is my question in [stackoverflow](https://stackoverflow.com/questions/66101993/grouping-and-searching-the-users-in-azure-b2c).

**Comment by ADefWebserver** [comment]
@vpallathu - Sorry I meant to say you can create **Groups** in **Azure B2C** and put users in those. That is what I cover here: https://blazorhelpwebsite.com/ViewBlogPost/43

If you need to read Attributes or roles for a user in **their** Azure Active Directory, you can use code at the bottom of this article: https://blazorhelpwebsite.com/ViewBlogPost/42

**Comment by vpallathu** [comment]
I was able to use the code from **edituser.razor**, and see the groups once I crated them in **AD**. My concern is that the pricing would go higher because I'm using both **AD** and **AD B2C**.
